apiVersion: v1
kind: Secret
metadata:
  name: supply-chain-secrets
  namespace: supply-chain
type: Opaque
stringData:
  POSTGRES_USER: "postgres_prod"
  POSTGRES_PASSWORD: "replace_with_base64_encoded_secure_postgres_password"
  REDIS_PASSWORD: "replace_with_base64_encoded_secure_redis_password"
  API_KEY: "replace_with_base64_encoded_secure_api_key"
